# Generated by Django 5.0.7 on 2024-07-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Transferee', 'Transferee'), ('Shiftee', 'Shiftee'), ('Late Filing', 'Late Filing'), ('Damaged', 'Damaged'), ('Old ID', 'Old ID'), ('Correction of Entry', 'Correction of Entry')], max_length=50)),
                ('academic', models.CharField(choices=[('LHS', 'LHS'), ('SHS', 'SHS'), ('Undergrad', 'Undergrad'), ('Graduate School', 'Graduate School'), ('Open University', 'Open University'), ('College of Law', 'College of Law'), ('Institute of Technology', 'Institute of Technology')], max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('student_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('dob', models.DateField()),
                ('college', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('emergency_address', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
